### ISSUE TITLE
JS bindings: App.list/byName/byPid return native instances, so subscribe() returns _NativeSubscription instead of EventEmitter Subscription

### ISSUE THREAD

**Issue by morrowgarrett** [xa11y/xa11y#113]
## Summary

In `@crowecawcaw/xa11y@0.6.1` (built from `origin/main` at `7ffd043`), the new Playwright-style `EventEmitter` API introduced in #109 is unreachable via the documented entry points. `App.list()`, `App.byName()`, and `App.byPid()` return instances of `native.App` whose prototype chain does not include the JS-wrapper `App`, so calling `.subscribe()` on them dispatches to the Rust binding and returns `_NativeSubscription` (which has only `start` / `drain` / `close`) rather than the `Subscription` class defined in `index.js` (which extends `EventEmitter` and has `.on()` / `.waitForEvent()`).

Result: the JSDoc example in `index.js:154` and the `index.d.ts` header example both fail at runtime with `TypeError: sub.on is not a function`.

## Minimal repro

```js
const { App, Subscription } = require('@crowecawcaw/xa11y');

const apps = await App.list();
const a = apps[0];

console.log(a instanceof App);              // true (from Symbol.hasInstance override)
console.log(typeof a.subscribe);            // 'function'

const sub = await a.subscribe();
console.log(sub.constructor.name);          // '_NativeSubscription'  ← bug
console.log(sub instanceof Subscription);   // false
console.log(typeof sub.on);                 // 'undefined'
console.log(typeof sub.waitForEvent);       // 'undefined'
```

Same issue via `App.byName()` and `App.byPid()`.

## Root cause

In `xa11y-js/index.js`:

```js
class App extends native.App {
  static async byName(name) {
    return await native.App.byName(name);   // returns native.App, not App
  }
  static async list() {
    return await native.App.list();          // returns Array<native.App>
  }
}
```

The static methods delegate to the parent's napi-exposed factories, which allocate `native.App` instances. JS class extension does not rewrite the prototype of values produced by the parent's static factories, so the wrapper's overrides (`async subscribe(opts)` returning an `EventEmitter` `Subscription`) are never reached.

The `Symbol.hasInstance` override on `App` masks the issue for `instanceof` checks but doesn't affect method dispatch, which uses the real prototype chain (`native.App.prototype`).

## Why CI didn't catch it

`__test__/types/consumers.test-d.ts` type-checks `sub.on('focusChanged', …)` and `sub.waitForEvent(…)`, but type-only checks don't exercise runtime prototypes.

No unit or integration test currently uses `subscribe()` or `waitForEvent` at runtime — grepping `__test__/unit/*.js` and `__test__/integ/*.js` for `subscribe` or `\.on(` returns nothing.

## Suggested fix

Rewire the prototype in the wrapper's static factories. ~3 lines, no Rust-side changes:

```js
class App extends native.App {
  static async byName(name) {
    try {
      const a = await native.App.byName(name);
      Object.setPrototypeOf(a, App.prototype);
      return a;
    } catch (err) {
      throw toTypedError(err);
    }
  }

  static async byPid(pid) {
    try {
      const a = await native.App.byPid(pid);
      Object.setPrototypeOf(a, App.prototype);
      return a;
    } catch (err) {
      throw toTypedError(err);
    }
  }

  static async list() {
    try {
      const apps = await native.App.list();
      for (const a of apps) Object.setPrototypeOf(a, App.prototype);
      return apps;
    } catch (err) {
      throw toTypedError(err);
    }
  }
  // …
}
```

Also worth adding a runtime unit test that confirms `(await App.list())[0].subscribe()` returns an instance of `Subscription` with a working `.on()` — otherwise the type-test alone will keep shielding this from CI.

## Workaround

Consumers can manually rewire today:

```js
const apps = await App.list();
const a = apps[0];
Object.setPrototypeOf(a, App.prototype);   // now a.subscribe() works as documented
const sub = await a.subscribe();
sub.on('focusChanged', (ev) => { /* ... */ });
```

## Environment

- `@crowecawcaw/xa11y@0.6.1` (not yet on npm — 0.6.1 publish failed at the npm step; this was built locally from `xa11y-js/` at `origin/main`).
- Node 20.20.2
- Ubuntu 24.04, GNOME 46, Wayland
- Discovered while running a cross-binding event-stream parity test against Python `xa11y==0.6.1` as part of Linux Phase B testing.

Happy to PR the fix above if you'd like — it's small enough to ship alongside a runtime test for the subscribe path.
